use_frameworks!

target 'SwiftGraphKit_Example' do
  pod 'SwiftGraphKit', :path => '../'

  target 'SwiftGraphKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
